name: Build

on:
  push:
    branches:
      - main


jobs:
  analyze:
    name: SonarQube analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  build_back:
    name: Build and push back
    runs-on: ubuntu-latest
    needs: analyze

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Build docker image back
      run: |
        cd backend 
        docker image build -t backend .
  
  build_front:
    name: Build and push front
    runs-on: ubuntu-latest
    needs: analyze

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Build docker image front
        run: |
          cd frontend
          docker image build -t frontend .
  


  
